import { Product, Category, Testimonial } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    name: 'New Baby',
    slug: 'new-baby',
    description: 'Gentle, heartwarming blooms to welcome precious new beginnings with sweetness and joy.',
    icon: 'baby',
    image: '/images/categories/new-baby.png',
  },
  {
    name: 'Anniversaries',
    slug: 'anniversaries',
    description: 'Timeless floral arrangements to celebrate lasting love and cherish every cherished milestone.',
    icon: 'bouquet',
    image: '/images/categories/anniversaries.png',
  },
  {
    name: 'Birthdays',
    slug: 'birthdays',
    description: 'Vibrant, celebratory bouquets designed to bring smiles and brighten unforgettable days.',
    icon: 'balloons',
    image: '/images/categories/birthdays.png',
  },
  {
    name: 'Roses',
    slug: 'roses',
    description: 'Classic luxury long-stemmed and garden roses hand-selected for unmatched beauty and scent.',
    icon: 'rose',
    image: '/images/categories/roses.png',
  },
  {
    name: 'Weddings',
    slug: 'weddings',
    description: 'Bespoke bridal bouquets and romantic ceremonial florals crafted for your most magical day.',
    icon: 'rings',
    image: '/images/categories/weddings.png',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    _id: 'prod-1',
    name: 'Velvet Plum Symphony',
    slug: 'velvet-plum-symphony',
    category: 'Anniversaries',
    price: 95,
    compareAtPrice: 130,
    images: ['/images/products/velvet-plum-symphony.jpg'],
    description: 'A rich harmony of purple and soft lavender chrysanthemums intertwined with delicate baby’s breath. Artfully hand-wrapped in layered lilac-blush paper and tied with an elegant satin ribbon.',
    details: [
      'Handcrafted with premium fresh chrysanthemums',
      'Accented with airy gypsophila baby’s breath',
      'Signature lilac-blush origami wrap with satin ribbon',
      'Includes hydration pack and flower food',
    ],
    featured: true,
    bestseller: true,
    stock: 18,
    tags: ['anniversaries', 'chrysanthemums', 'lilac', 'romantic', 'bestseller'],
    rating: 4.9,
    reviewsCount: 42,
  },
  {
    _id: 'prod-2',
    name: 'Blush Lilac Serenade',
    slug: 'blush-lilac-serenade',
    category: 'Birthdays',
    price: 85,
    compareAtPrice: 120,
    images: ['/images/products/blush-lilac-serenade.jpg'],
    description: 'A lush celebratory bouquet of pure white and magenta-violet chrysanthemums sprinkled with cloud-soft baby’s breath, nestled in pristine white wrap with a cream ribbon.',
    details: [
      'Freshly harvested vibrant chrysanthemums',
      'Crisp white boutique wrap with ivory bow',
      'Perfect for birthdays and uplifting moments',
      'Long-lasting vase life 10–14 days',
    ],
    featured: true,
    bestseller: true,
    stock: 24,
    tags: ['birthdays', 'chrysanthemums', 'violet', 'celebration', 'bestseller'],
    rating: 4.8,
    reviewsCount: 35,
  },
  {
    _id: 'prod-3',
    name: 'Golden Sunburst Delight',
    slug: 'golden-sunburst-delight',
    category: 'Birthdays',
    price: 110,
    compareAtPrice: 145,
    images: ['/images/products/golden-sunburst-delight.jpg'],
    description: 'Radiant golden sunflowers paired with crisp white roses, white tulips, and delicate gypsophila. Tied with a silky ivory bow for an instant dose of pure morning warmth.',
    details: [
      'Vibrant golden sun-grown sunflowers',
      'White roses and fresh spring tulips',
      'Soft blush-pink wrap with silk ribbon',
      'Includes personalized handwritten greeting card',
    ],
    featured: true,
    bestseller: true,
    stock: 15,
    tags: ['birthdays', 'sunflowers', 'roses', 'tulips', 'bestseller'],
    rating: 5.0,
    reviewsCount: 48,
  },
  {
    _id: 'prod-4',
    name: 'Cotton Candy Whispers',
    slug: 'cotton-candy-whispers',
    category: 'Anniversaries',
    price: 80,
    compareAtPrice: 110,
    images: ['/images/products/cotton-candy-whispers.jpg'],
    description: 'Soft confectioner-pink and snow-white chrysanthemums surrounded by clouds of baby’s breath in artisanal crinkled rose wrap. Delicate, sweet, and romantic.',
    details: [
      'Pastel pink and white pom-pom chrysanthemums',
      'Lush gypsophila filler clouds',
      'Tied with a silky rose-pink satin bow',
      'Stem life approx. 12–15 days',
    ],
    featured: false,
    bestseller: true,
    stock: 20,
    tags: ['anniversaries', 'pastel', 'chrysanthemums', 'romantic'],
    rating: 4.8,
    reviewsCount: 29,
  },
  {
    _id: 'prod-5',
    name: 'Imperial Rose & Lily Fantasy',
    slug: 'imperial-rose-lily-fantasy',
    category: 'Weddings',
    price: 165,
    compareAtPrice: 210,
    images: ['/images/products/imperial-rose-lily-fantasy.jpg'],
    description: 'Grand Stargazer oriental lilies combined with velvety white and pink roses, framed in crisp layered cream and gold kraft paper. The epitome of couture bridal elegance.',
    details: [
      'Fragrant Stargazer oriental lilies',
      'Hand-selected premium bridal roses',
      'Layered champagne and gold origami wrap',
      'Hydration base for maximum freshness',
    ],
    featured: true,
    bestseller: true,
    stock: 12,
    tags: ['weddings', 'roses', 'lilies', 'luxury', 'bestseller'],
    rating: 5.0,
    reviewsCount: 56,
  },
  {
    _id: 'prod-6',
    name: 'Majestic Lily Charm',
    slug: 'majestic-lily-charm',
    category: 'Weddings',
    price: 135,
    compareAtPrice: 175,
    images: ['/images/products/majestic-lily-charm.jpg'],
    description: 'Vibrant magenta Stargazer lilies, delicate pink roses, and white pom-pom blooms in royal lilac pleated wrap. An unforgettable statement of grace and celebration.',
    details: [
      'Exotic deep magenta lilies and roses',
      'Royal purple fan-pleated couture wrapping',
      'Rich floral fragrance',
      'Includes flower food and care booklet',
    ],
    featured: true,
    bestseller: true,
    stock: 14,
    tags: ['weddings', 'lilies', 'roses', 'luxury'],
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    _id: 'prod-7',
    name: 'Royal Crimson Rajnigandha',
    slug: 'royal-crimson-rajnigandha',
    category: 'Roses',
    price: 140,
    compareAtPrice: 180,
    images: ['/images/products/royal-crimson-rajnigandha.jpg'],
    description: 'An architectural starburst of deep red velvet roses and intensely fragrant fresh white tuberoses (rajnigandha) in dramatic black and gold origami paper.',
    details: [
      'Velvety crimson Dutch roses',
      'Freshly cut fragrant tuberoses (rajnigandha)',
      'Structured star-shaped origami black & gold wrap',
      'Captivating exotic aroma that fills the room',
    ],
    featured: true,
    bestseller: true,
    stock: 16,
    tags: ['roses', 'rajnigandha', 'crimson', 'fragrant', 'bestseller'],
    rating: 4.9,
    reviewsCount: 62,
  },
  {
    _id: 'prod-8',
    name: 'Plush Petals Baby Haven',
    slug: 'plush-petals-baby-haven',
    category: 'New Baby',
    price: 150,
    compareAtPrice: 195,
    images: ['/images/products/plush-petals-baby-haven.jpg'],
    description: 'Sweet plush animal companions (teddy bear, puppy, bunny, elephant) nestled among soft pink and ivory roses in modern black and gold wrap with a pink satin bow.',
    details: [
      'Includes 4 adorable plush keepsake baby toys',
      'Fresh pastel pink and ivory spray roses',
      'Black and gold luxury pleated wrap with pink bow',
      'Safe for nurseries and perfect for baby showers',
    ],
    featured: true,
    bestseller: true,
    stock: 10,
    tags: ['new baby', 'plush toy', 'baby shower', 'roses', 'bestseller'],
    rating: 5.0,
    reviewsCount: 44,
  },
  {
    _id: 'prod-9',
    name: 'Rustic Heart Sunflower Bloom',
    slug: 'rustic-heart-sunflower-bloom',
    category: 'Anniversaries',
    price: 125,
    compareAtPrice: 160,
    images: ['/images/products/rustic-heart-sunflower-bloom.jpg'],
    description: 'Golden sunflowers, aromatic eucalyptus, and baby’s breath framed by a handcrafted heart-shaped grapevine wreath in warm golden wrap with black ribbon.',
    details: [
      'Handcrafted natural grapevine heart frame',
      'Golden giant sunflowers & wild eucalyptus',
      'Warm bronze and gold fluted paper wrap',
      'Symbolic expression of everlasting love',
    ],
    featured: true,
    bestseller: true,
    stock: 14,
    tags: ['anniversaries', 'sunflowers', 'heart', 'rustic', 'bestseller'],
    rating: 5.0,
    reviewsCount: 51,
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    _id: 'test-1',
    name: 'Sophia Laurent',
    email: 'sophia.laurent@example.com',
    message: 'The Floral Fantasy arrangement took our anniversary dinner to another level. The roses were so fresh they lasted two full weeks in our living room. Truly the highest standard in floral artistry!',
    rating: 5,
    approved: true,
    createdAt: '2026-03-12T10:30:00.000Z',
  },
  {
    _id: 'test-2',
    name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    message: 'Ordered the Rose Perfection for my mother’s 60th birthday. The white pleated packaging and pink satin ribbon were utterly breathtaking. Rutuja Florals is my forever favorite boutique.',
    rating: 5,
    approved: true,
    createdAt: '2026-03-15T14:20:00.000Z',
  },
  {
    _id: 'test-3',
    name: 'Camille Dubois',
    email: 'camille.d@example.com',
    message: 'Remarkable attention to detail, speedy delivery, and flowers that smelled heavenly. The website was so smooth and beautiful to order from. 10/10 recommend!',
    rating: 5,
    approved: true,
    createdAt: '2026-03-18T09:15:00.000Z',
  },
];
